//
//  Generated file. Do not edit.
//

// This file is auto-generated by `flutter pub get` / `flutter build`.
// It will be overwritten with the real plugin registration list the first
// time the Flutter tool runs against this project. The placeholder below
// only exists so Xcode has something to compile before that first run.

#ifndef GeneratedPluginRegistrant_h
#define GeneratedPluginRegistrant_h

#import <Flutter/Flutter.h>

@interface GeneratedPluginRegistrant : NSObject
+ (void)registerWithRegistry:(NSObject<FlutterPluginRegistry>*)registry;
@end

#endif /* GeneratedPluginRegistrant_h */
