//
// Generated file. Do not edit.
//

// This file is auto-generated by `flutter pub get` / `flutter build linux`,
// based on the plugins declared in pubspec.yaml. It will be overwritten the
// first time the Flutter tool runs against this project.

#include "generated_plugin_registrant.h"

void fl_register_plugins(FlPluginRegistry* registry) {
  // Plugin registration calls will be generated here by the Flutter tool
  // once `flutter pub get` has resolved pubspec.yaml.
}
