//
// Generated file. Do not edit.
//

// This file is auto-generated by `flutter pub get` / `flutter build windows`,
// based on the plugins declared in pubspec.yaml. It will be overwritten the
// first time the Flutter tool runs against this project.

#ifndef GENERATED_PLUGIN_REGISTRANT_
#define GENERATED_PLUGIN_REGISTRANT_

#include <flutter/plugin_registry.h>

// Registers Flutter plugins.
void RegisterPlugins(flutter::PluginRegistry* registry);

#endif  // GENERATED_PLUGIN_REGISTRANT_
